<?php

/**
 * @file
 * Functions to support theming.
 */

/**
 * Implements hook_preprocess_block().
 */
function emulsify_preprocess_block(&$variables) {
  // Check if the block is being placed on a node page.
  if (\Drupal::routeMatch()->getRouteName() == 'entity.node.canonical') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node) {
      // Pass the node title to the block template.
      $variables['node_title'] = $node->getTitle();
    }
  }
}
